site_name: Madek Docs
docs_dir: source
site_dir: build
markdown_extensions: [tables, fenced_code, footnotes]
theme: readthedocs
extra_css: ['style.css']

#  tmp: does not work but should:
# markdown_extensions: [tables, fenced_code, wikilinks(base_url='/wiki/', end_url='.html')]
